import 'package:am3_taller/models/genre.dart';

final List<Genre> moviesCategory = [
  Genre(id: 12, name: 'Aventura'),
  Genre(id: 14, name: 'Fantasía'),
  Genre(id: 16, name: 'Animación'),
  Genre(id: 18, name: 'Drama'),
  Genre(id: 27, name: 'Terror'),
  Genre(id: 28, name: 'Acción'),
  Genre(id: 35, name: 'Comedia'),
  Genre(id: 36, name: 'Historia'),
  Genre(id: 37, name: 'Western'),
  Genre(id: 53, name: 'Suspense'),
  Genre(id: 80, name: 'Crimen'),
  Genre(id: 99, name: 'Documental'),
  Genre(id: 878, name: 'Ciencia ficción'),
  Genre(id: 9648, name: 'Misterio'),
  Genre(id: 10402, name: 'Música'),
  Genre(id: 10749, name: 'Romance'),
  Genre(id: 10751, name: 'Familia'),
  Genre(id: 10752, name: 'Bélica'),
  Genre(id: 10759, name: 'Action & Adventure'),
  Genre(id: 10762, name: 'Kids'),
  Genre(id: 10763, name: 'News'),
  Genre(id: 10764, name: 'Reality'),
  Genre(id: 10765, name: 'Sci-Fi & Fantasy'),
  Genre(id: 10766, name: 'Soap'),
  Genre(id: 10767, name: 'Talk'),
  Genre(id: 10768, name: 'War & Politics'),
  Genre(id: 10770, name: 'Película de TV'),
];
